version: 2.1
executors:
  default:
    docker:
      - image: golang:1.13
    working_directory: /go/src/github.com/0daryo/monkey
    environment:
      GOPATH: /
      GOCACHE: /.cache/go-build
      GO111MODULE: "on"
commands:
  go_mod_download:
    steps:
      # - restore_cache:
      #     name: Restore go modules cache
      #     keys:
      #       - go-modules-{{ checksum "go.sum" }}

      - run: go mod download

      # - save_cache:
      #     name: Save go modules cache
      #     key: go-modules-{{ checksum "go.sum" }}
      #     paths:
      #       - "/go/pkg/mod"

jobs:
  build:
    executor: default
    steps:
      - checkout
      - checkout
      - go_mod_download
  lint:
    executor: default
    steps:
      - checkout
      - go_mod_download

      - run:
          name: Install GolangCI-Lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.18.0

      - run:
          name: Run GolangCI-Lint
          command: ./bin/golangci-lint run --issues-exit-code 0 --out-format checkstyle
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: Run Tests
          command: go test -race -v ./...

workflows:
  golang-workflow:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
